### ISSUE TITLE
Feature request - progress endpoint

### ISSUE THREAD

**Issue by weaklysubjective** [lightninglabs/neutrino#119]
When a new node is started up, it takes approximately 25 minutes for the LND daemon to start up and listen on port 9735. Neutrino is awesome and is building filters at a rapid pace. Yet in a mobile environment, apart from training videos, documentation, there is no other way to provide a feedback or a progress bar as to the status of neutrino while it is trying to fully sync. 

Thinking a progress endpoint would be great with at least two fields, 1) Caught up with block, 2) total blocks - something like 140000/1,4000,000. We could then use the data to post a progress bar.
This would be for the very first time the node is created, and it would be useful even subsequently, only that the syncing process is generally finished in under 30 seconds (depending on how the mobile node has been off line).

**Comment by Roasbeef** [comment]
Closing this now as set up is much faster.
