### ISSUE TITLE
Error on building the latest master without GO111MODULE=on

### ISSUE THREAD

**Issue by tiero** [lightninglabs/neutrino#125]
Runnning `go build` it returns

```
# github.com/lightninglabs/neutrino
neutrino/neutrino.go:1206:4: cannot use sp.OnVersion (type func(*peer.Peer, *wire.MsgVersion) *wire.MsgReject) as type func(*peer.Peer, *wire.MsgVersion) in field value
neutrino/rescan.go:982:22: undefined: txscript.ComputePkScript
```

**Comment by tiero** [comment]
I have actually followed the steps in travis.yml and with both `go build` and `go build ./...` all exit without errors, but I cannot find the binaries 🤔 It is supposed to be used only as go package?

Sorry for the dumb question

**Comment by Mimble-Wimble** [comment]
@tiero, how did you manage to set GO11MODULE to on? I keep receiving the following error:
```
warning: modules disabled by GO111MODULE=auto in GOPATH/src;
	ignoring go.mod;
```

**Comment by tiero** [comment]
> @tiero, how did you manage to set GO11MODULE to on? I keep receiving the following error:
> 
> ```
> warning: modules disabled by GO111MODULE=auto in GOPATH/src;
> 	ignoring go.mod;
> ```

`export GO111MODULE=on`

Maybe your something override your path

**Comment by Mimble-Wimble** [comment]
Ahhhh, gotcha. Looks like that might be it.
