### ISSUE TITLE
Clarify roasbeef dependencies

### ISSUE THREAD

**Issue by stevenroose** [lightninglabs/neutrino#13]
Currently the glide.yaml file has the btcsuite dependencies replaces with the forks on roasbeefs account. That's fair enough.

I would however suggest the following:
- Specify the version as a branch instead of a commit hash. This makes it easier to follow the changes that will end up here.
- Keep a list in this repo with the features that btcsuite is lacking in order to switch back to btcsuite.

**Comment by Roasbeef** [comment]
No longer applies.
