### ISSUE TITLE
Can neutrino get the merkle proof of a transaction? And calculate it ?

### ISSUE THREAD

**Issue by Zou-XueYan** [lightninglabs/neutrino#165]

**Comment by Roasbeef** [comment]
No. We don't use BIP 37. Check out BIP 157+158 for details w.r.t how the protocol works.

**Comment by cfromknecht** [comment]
If you know what block the transaction is in, you could use neutrino to query the network for the block. `btcutil` has some code for generating merkle proofs if you also have a filter, but that could be modified to just prove a particular index if that's all you need
