### ISSUE TITLE
banman: unable to initialize ban store: bucket already exists

### ISSUE THREAD

**Issue by Wowee0** [lightninglabs/neutrino#172]
LND/Neutrino chokes at startup with this error when initializing banman.  It appears from line 92 of banman/store.go as CreateTopLevelBucket errors if the storage bucket already exists.  Locally solved by the following patch: 

    	banStore, err := tx.CreateTopLevelBucket(banStoreBucket)
    	if err != nil {
    		// unable to initialize ban store: bucket already exists
    		banStore = tx.ReadWriteBucket(banStoreBucket)
    		if banStore == nil {
    			return err
    		}
    	}

Please let me know if you would accept a PR to address this.

**Comment by wpaulino** [comment]
Will be fixed as part of https://github.com/lightninglabs/neutrino/pull/171.
