### ISSUE TITLE
How to build and run?

### ISSUE THREAD

**Issue by nharmon9** [lightninglabs/neutrino#195]

**Comment by yyforyongyu** [comment]
I think `neutrino` is meant to be used as a package/library for now. As stated in the `README.md`,

> The client is instantiated as an object using `NewChainService` and then started.

**Comment by NotASithLord** [comment]
Might still be useful for someone who wants to quickly see it in action from the command line if there's an easy path to doing so.

**Comment by halseth** [comment]
Duplicate of https://github.com/lightninglabs/neutrino/issues/202
