### ISSUE TITLE
Unable to query bootstrapper BOLT-0010 DNS Seed 

### ISSUE THREAD

**Issue by 6hundred** [lightninglabs/neutrino#22]
keep on getting this on Mac, sent a tx from faucet. received nothing so far. 

lnd: 2017-10-14 21:54:12.334 [INF] DISC: Attempting to bootstrap with: BOLT-0010 DNS Seed: [nodes.lightning.directory]
lnd: 2017-10-14 21:54:12.993 [ERR] DISC: Unable to query bootstrapper BOLT-0010 DNS Seed: [nodes.lightning.directory]: lookup _nodes._tcp.nodes.lightning.directory on [2602:306:3028:ece0::1]:53: no such host 2017-10-14 21:54:12.993 [INF] DISC: Obtained 0 addrs to bootstrap network with
lnd: 2017-10-14 21:54:23.640 [INF] RPCS: [listchannels] fetched 0 channels from DB

**Comment by Roasbeef** [comment]
Addressed by https://github.com/lightningnetwork/lnd/commit/5b226a9d37b3a9d0b2f874f40d50d4c575ff0e55

Closing.
