### ISSUE TITLE
Unable to neutrino.connect to tor v3 bitcoind onions running compact filters from LND

### ISSUE THREAD

**Issue by githorray** [lightninglabs/neutrino#223]
lnd version: lnd version 0.13.0-beta.rc3 commit=v0.13.0-beta.rc3-26-gad0ecc4d

lnd.conf entry:

`neutrino.connect=[tor_v3].onion`

lnd errors:

`[WRN] BTCN: unable to lookup IP for [tor_v3].onion: invalid onion v2 host: [tor_v3].onion`

**Comment by Roasbeef** [comment]
See https://github.com/lightningnetwork/lnd/issues/4973

**Comment by lukaszsamson** [comment]
@Roasbeef https://github.com/lightningnetwork/lnd/issues/4973 is now closed. Will it now be possible to get compact filters from v3 tor nodes in lnd 0.15 or does it require further work?

**Comment by guggero** [comment]
Fixed by https://github.com/lightningnetwork/lnd/issues/4973, `lnd v0.15.0-beta` will support using tor v3 compact filter sources.
