### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by iBobik** [lightninglabs/neutrino#225]
> There are multiple [known major issues](https://github.com/lightninglabs/neutrino/issues) with the client, so it is **not recommended** to use it with real money at this point.

This sentence pro README is 4 years old. I see is only one open P1 issue (#218) and it is not clear why I should not use Neutrino for real money. Or P1 are not "major issues"?

Could it be used in production with real money? What's the risk today? What are we waiting for "production readiness"?

**Comment by Roasbeef** [comment]
Yeah it's actively used on mainnet as is, we've just forgotten to remove that section from the README. We have a release upcoming in the next few weeks, so we'll definitely update it before then.

**Comment by iBobik** [comment]
Hi, what now? :-)

**Comment by philipp1992** [comment]
?
