### ISSUE TITLE
issues running bitcoin lightning wallet

### ISSUE THREAD

**Issue by shedy360** [lightninglabs/neutrino#238]
Hi I needed to make a payment via lightning and i downloaded the Lightning-win32v0.5.9-alpha client on my windows 10 64 bit laptop, while setting up i got the seed key and wallet address for funding and went on to send some onchain btc to the address, the btc is yet to show up on the lightning wallet. Now whenever i launch the app its either i get ln1 below or when it lets me in to the next screen ln2, Ive attached some screenshots. Need fast help with this as i need to make the payment urgently. Thanks in advan
![ln2](https://user-images.githubusercontent.com/57156817/143838687-68589854-efc8-4f49-8225-01289fb8019b.png)
![ln4](https://user-images.githubusercontent.com/57156817/143838693-03db0710-1b64-4ad7-b922-b08d16f7d6c1.png)
![ln1](https://user-images.githubusercontent.com/57156817/143838695-2ae4164a-7415-4bb1-b01b-5143cf46daa9.png)
ce

**Comment by guggero** [comment]
That app has been decommissioned and shouldn't be used anymore. Try restoring the same seed in another wallet, for example https://github.com/LN-Zap/zap-desktop which is still maintained.
