### ISSUE TITLE
Mobile Support

### ISSUE THREAD

**Issue by mkohlhaas** [lightninglabs/neutrino#284]
Sorry for being ignorant. But what is the preferred way to include `neutrino` into an Android/iOS app? Is the library designed to be conformant with [`gomobile`](https://github.com/golang/mobile)?

Kind regards!

**Comment by guggero** [comment]
Neutrino is a Golang library for all the light client validation code. But it doesn't have its own standalone binary. So you'd use Neutrino in a wallet app that's written in Golang and then use `gomobile` on that. For example, that's how `lnd` is using Neutrino. And this is where we generate the mobile bindings for `lnd` in general: https://github.com/lightningnetwork/lnd/tree/master/mobile

**Comment by mkohlhaas** [comment]
Cool. Thank you!
