### ISSUE TITLE
 The program is stuck, please help

### ISSUE THREAD

**Issue by penglipeng666** [lightninglabs/neutrino#301]
My operating environment is lit 0.12.2，btc is mainnet。

specific situation: 
  I transferred taproot assets. After the transfer was successful, when btc confirmed it, two alarms appeared. Then the program got stuck, and there was no new log printing. After restarting, it was still stuck. Here are two alarms:
“2024-07-09 09:20:02.078 [WRN] LNWL: Query(0) from peer 108.94.105.78:8333 failed, rescheduling: did not get response before timeout
2024-07-09 09:20:06.080 [WRN] LNWL: Query(0) from peer [2a02:c206:3012:8083::1]:8333 failed and reached maximum number of retries, not rescheduling: did not get response before timeout”

I don't know where the problem lies now. Is there a problem with neutrinos finding btc nodes? I hope you can provide me with some opinions. Thank you so much!

I tried replacing these three files and it started successfully, but I don't know why:
![image](https://github.com/lightninglabs/neutrino/assets/44795722/c6c92037-7458-4421-b765-68992bdf9d70)

Because I found that they can be used as snapshots to make the first boot faster.

lit.conf:
lnd-mode=integrated
uipassword=11111111
network=mainnet
lnd.alias=lnd1
lnd.bitcoin.active=true

lnd.bitcoin.node=neutrino
lnd.rpclisten=0.0.0.0:10009
lnd.rpcmiddleware.enable=true
lnd.db.bolt.auto-compact=true
autopilot.disable=true
lnd.bitcoin.mainnet=true
lnd.neutrino.persistfilters=true
taproot-assets.network=mainnet
lnd.neutrino.feeurl=https://nodes.lightning.computer/fees/v1/btc-fee-estimates.json
lnd.neutrino.broadcasttimeout=11s
taproot-assets.universe.federationserver=202.79.173.41:8443

**Comment by Roasbeef** [comment]
Once you have enough peers, you should be able to make forward progress. How many peers does the neutrino node have?

**Comment by penglipeng666** [comment]
I copied it from somewhere else

**Comment by penglipeng666** [comment]
I did not specify a specific node for the neutrino connection, it looked for it on its own

**Comment by penglipeng666** [comment]
I searched for answers on the Internet and found something similar to this question:https://github.com/lightningnetwork/lnd/issues/8157

**Comment by penglipeng666** [comment]
I added several "neutrino.addpeer" to the configuration file and still couldn't solve it. But when I changed one of them to "neutrino.connect", it was successfully solved. Then I changed it back to "addpeer" and it ran normally.
