### ISSUE TITLE
Implement a batched version of GetUtxo

### ISSUE THREAD

**Issue by simonhorlick** [lightninglabs/neutrino#39]
An application that requires many concurrent calls to GetUtxo will find that it requests the same blocks from the network multiple times. A batched version of `GetUtxo` could solve this and would also reduce the amount of IO by not repeatedly fetching the same filters.

Implementation plan:
Create a filter consisting of all outpoints in the query.
Figure out which blocks might match by requesting all relevant filters.
Grab those blocks from the network and check the transactions.

**Comment by halseth** [comment]
Caching blocks could also help

**Comment by simonhorlick** [comment]
I also noticed that getting cfilters one-by-one is really killing performance, especially in the expected case where the neutrino server is far away. I want to also try grabbing them in parallel.

**Comment by Roasbeef** [comment]
@simonhorlick we plan to modify the message that neutrino uses to fetch filters to allow _batch_ fetching. This would mean when syncing from offline, we can pipeline all the messages from node to client. Also we can add prefetching heuristics to speculatively fetch filters within reason.

**Comment by simonhorlick** [comment]
Great, that sounds like it would help a lot.
