### ISSUE TITLE
[Questions] Privacy, Mainnet usage

### ISSUE THREAD

**Issue by nopara73** [lightninglabs/neutrino#44]
Did anyone evaluated the privacy properties of this client? If so, can you link it?

Do people use Neutrino on the mainnet? If I'm not mistaken the lnd daemon can use Neutrino as the back end currently. Is that right?

  As a background, I'd like to change [HiddenWallet](https://github.com/nopara73/HiddenWallet)'s back end to Neutrino (HiddenWallet is a full block downloading SPV wallet) if I find its privacy properties sufficient.
  I'm also thinking of implementing Neutrino from scratch in .NET, but I'm not sure that's a good approach. At such early stages competing implementations are just asking for trouble.

**Comment by nopara73** [comment]
After researching for some hours I got clear answers, so I'll answer my own questions.

> Did anyone evaluated the privacy properties of this client? If so, can you link it?

I cannot poke a hole on it, other than super theoretical stuff. I'd still read a link if provided.

> Do people use Neutrino on the mainnet? If I'm not mistaken the lnd daemon can use Neutrino as the back end currently. Is that right?

Yes to both.

**Comment by Zou-XueYan** [comment]
How to use neutrino to connect mainnet? Can you show me a demo code? appreciate very much！
