### ISSUE TITLE
Why is the Index so big?

### ISSUE THREAD

**Issue by nopara73** [lightninglabs/neutrino#46]
On the [mailing list](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2017-June/014474.html) you say the "the total size of the index comes out to 6.9GB."  

I was not able to fully understand your scheme, so I decided to scratch up my own simplified version of it: [Client Side Filtering--](https://github.com/nopara73/ClientSideFilteringMinusMinus/blob/master/README.md) until mainnet nodes start to serve Neutrino. In my version, the index is 1.75GB, despite zero optimization, using some old, inefficient code of mine.

**Comment by Roasbeef** [comment]
The _total_ filter size is around 7GB. The regular filter size is around 3GB. The regular filter contains:
  * The txid of each transaction
  * The pkScripts each output creates
  * The prevout that each input consumes

We use an `fp` rate of `2^-20`. We provide the prevout as otherwise, it would be impossible for a node that's at tip to create the index from scratch. Additionally this provides more flexibility for protocols building on top of `neutrino`.

**Comment by Roasbeef** [comment]
I'm not sure the motivation of your simplified construction as in a world where most full nodes serve the filters, that seems superior to depending on a centralized service.

**Comment by Roasbeef** [comment]
Also as you're just using 4 bytes of sha1 (which really shouldn't be used at all anymore...), then this means that the clients will have a greater _expected bandwidth_ as they'll be fetching more blocks due to collisions.

**Comment by nopara73** [comment]
I see why it is bigger then. @Roasbeef Our data structures are different. You store txids, pkScripts and prevouts (txid-index pair.) Your rationale for this is, otherwise it would take already synced nodes quite a lot of time to construct the index.  

My data structure is (a block filter):  

- The pkScripts of each outputs (not per transaction, but per block)  
- The pkScripts of each inputs

From this information the client knows which block it is interested, it is indeed a lot of work for a full node to create this index.

> I'm not sure the motivation of your simplified construction as in a world where most full nodes serve the filters, that seems superior to depending on a centralized service.

I had three reasons:  

1. Learning: I cannot understand anything that I didn't come up with. There is a saying: "Don't disassemble the frog, build it!"
2. My initial plan was using `lnd`, but I need to do quite a lot of things I cannot with `lnd`. I expect this to change in the future, but I suspect it's years away. The point of `lnd` is bringing LN to devs, keeping main chain devs happy is secondary.
3. And the third reason was, that I was browsing `lnd` issues and saw, right now the only way to use Neutrino on the mainnet is to setup my own `btcd` node that can serve it, which defeats the purpose for now.

I will either build my own Neutrino or use `lnd` in the future when it matures. I suspect for a couple of years I'm better off with Client Side Filtering --. Its lack of complexity prevents me from making mistakes and bugs.

> Also as you're just using 4 bytes of sha1 (which really shouldn't be used at all anymore...), then this means that the clients will have a greater expected bandwidth as they'll be fetching more blocks due to collisions.

I believe you refer to [the collision attacks](https://github.com/nopara73/HiddenWallet/issues/76#issuecomment-342511438) of sha1. I encountered with this before, but I believe it's not an issue here, since the back end is trusted.  Do you agree? Nevertheless you are more knowledgeable in this field and I am happy to accept suggestions to fast hash functions.

About collisions, 4 bytes will likely result in a few thousand collisions (I'm running the final tests with the whole blockchain, my estimates are based on only from samples). There is a couple of argument about its tolerability:  

- Chances are small that the addresses of my clients will have the collisions (yet to be seen, based on my running test).  
- My clients will know it doesn't have to download blocks before the wallet was created. In fact, this is the way HiddenWallet currently does works: it downloads all blocks from the creation of the wallet.  
- I am not writing a desktop software.
- I will download a unrelated blocks I am not interested in anyway to improve privacy.

**Comment by Roasbeef** [comment]
>  You store txids, pkScripts and prevouts (txid-index pair.) 

We don't store anything. All these items are put thru `siphash` then used to construct the filter.

> Your rationale for this is, otherwise it would take already synced nodes quite a lot of time to construct the index.

No. I mean that if you use the input's prev pk script, then this requires nodes to have a _txindex_ in order to build the index from scratch. As is, nodes just need the block themselves, so we support nodes building the index from scratch after updating. 

> I believe you refer to the collision attacks of sha1. I encountered with this before, but I believe it's not an issue here, since the back end is trusted. Do you agree?

Even aside from that, why use legacy mostly broken crypto? Just use sha2 and truncate that if this is the path you want to go with. 

> My initial plan was using lnd, but I need to do quite a lot of things I cannot with lnd. I expect this to change in the future, but I suspect it's years away. The point of lnd is bringing LN to devs, keeping main chain devs happy is secondary.

Years? Nah more like months. I anticipate the BIP being included in a version of `bitcoind` sometime this year. Also we're pretty close to getting all of our changes back into `btcd` so people can start running it on mainnet. 

If you want to go with the server mode, then you can use btcd's RPC interface. The interface lets you fetch filters for each block. The wallet can then manually query the filters and fetch blocks as required.

**Comment by nopara73** [comment]
> Even aside from that, why use legacy mostly broken crypto? Just use sha2 and truncate that if this is the path you want to go with.  

Fair enough. I changed it to sha256. 

On another related note. Today @lontivero finished the Golomb-Rice coding implementation in .NET:  
https://github.com/lontivero/GolombCodedFilterSet  
So I created the tests, replacing the sha hashing with the filters and I got these results. This is with my data structure not with yours:  

For today's 150GB blockchain my gzip compressed Index file was:
- For P=4 -> 1 GB
- For P=8 -> 1.5 GB
- For P=10 -> 3 GB

In 700 blocks, for 1000 newly generated addresses:
- P=10 -> 6 false positive match found
- P=4 -> 700 false positive match found

Just to make sure, do these values seem to be right?

To reiterate my Index looks like this:  
```
blockHeight:blockHash
golomb-rice filter of scriptPubKeys (both outputs and previns)
blockHeight:blockHash
golomb-rice filter of scriptPubKeys (both outputs and previns)
blockHeight:blockHash
golomb-rice filter of scriptPubKeys (both outputs and previns)
```

**Comment by nopara73** [comment]
For comparision, the same estimation gives these values for my data method (which are worse, than my initial estimation was, and now I know that I cannot use hash length 4, as you suggested):

In 700 blocks, for 1000 newly generated addresses
hash length = 4 -> 134 collision, 3GB Index size for today's 150GB blocksize
hash length = 5 -> 11 collision, 3.8GB Index size for today's 150GB blocksize
hash length = 6 -> 0 collision, 4.6GB Index size for today's 150GB blocksize

**Comment by Roasbeef** [comment]
My recommendation would just be to use the `btcd` RPC interface for now (if you're already going the server route). If you have the GCS set implementation, then you can query against the returned filters from RPC. 

> For P=10 -> 3 GB

P=2^10 is pretty low. But yes, if you have less items in the filter the total size may be smaller. We wrote a tool for computing these probabilities and the FP impact based on the number of queries: https://aakselrod.github.io/gcs_calc.html

I don't think it makes sense for you to roll your own protocol, when the three major node implementations (`bitcoind`, `bcoin`, `btcd`) are planning to implement BIP 157+158.

**Comment by nopara73** [comment]
Just an update on what we decided on.  
We are going to use GCS set implementation, but we will go with our data structure. We will redesign it when Core nodes start serving Neutrino.  

Furthermore we are also planning to PR GCS implementation into NBitcoin.

We will use P=20, as you suggested.

What we plan to do is: since HiddenWallet is a bech32 only wallet, we don't bother with other scripts.  
We will setup a server, which will serve clients with an Index with the following data structure:

`{blockHeight}:{blockHash}{scriptPubKeys (both spent and funded) in Golomb filter.}  

The scriptPubKeys will only contain native segwit scripts (p2wpkh.) This also gives us the opportunity to start building our Index from the first ever p2wpkh payment.  
This will likely result in a few MB of Index size and will stay low until bech32 adoption catches on. I suspect by the time it happens Neutrino will be served by Core, therefore we can pivot to that with some performance decrease of course, which is a fine compromise for decentralization.
