### ISSUE TITLE
How should empty filters be serialized?

### ISSUE THREAD

**Issue by lontivero** [lightninglabs/neutrino#56]
I'm implementing the data structures and algorithms for bip157 and bip158 in NBitcoin. Using the [test vectors referenced by the bip158 document](https://github.com/bitcoin/bips/blob/master/bip-0158/testnet-20.csv) i see that block height=0 (genesis) and block height=1 have an empty extended filter becuase they only have one transaction each without inputs (the coinbase tx). However those two empty filters are serialized differently, the first one is serialized as `"00"` and the second one is serialized as `""` (empty string).

Are both correct? Should I check for `filter.N > 0` before comparing their serialized representation?

PS: i'm not sure is this is the correct project where to make this question so, please let me know it. Thx

**Comment by Roasbeef** [comment]
The test vectors haven't yet been updated to use the new serialization format (just now realizing?), and also the inclusion of the txid in the regular filter. So a regular filter cannot be empty. In a prior version, the size of the filter was a fixed 4-byte integer. In the current version, it uses a varint which should be a single 0x00 byte serialized.
