### ISSUE TITLE
consistently crash on simnet when restarting after some blocks were mined

### ISSUE THREAD

**Issue by roeierez** [lightninglabs/neutrino#97]
This issue is about a crash we having and we managed create a reproducer on simnet.
I have a setup of:
* 2 Lnd nodes updated to master
* 1 Btcd node configured to work with compact filters updated to master.

Both of them configured to work on simnet.

I am then executing the following steps: 
1. run all nodes
2. mine 400 blocks
3. open channel from one lnd node to another
4. generate 6 blocks for channel to open
5. stop lnd node
6. mine one block
7. restart lnd

Result:
lnd crashes consistently on every restart. Only after I mine 1000 blocks is sometimes recover and runs.

This is the log for the first restart crash
[first_restart.txt](https://github.com/lightninglabs/neutrino/files/2384007/first_restart.txt)

And this one is for the second restart (it is different a bit)
[second_restart.txt](https://github.com/lightninglabs/neutrino/files/2384010/second_restart.txt)

**Comment by roeierez** [comment]
After more investigation, I have some input to share:
When lnd starts it initiate a GetUTXO request which triggers a rescan.
I followed this rescan down to the function in blockManager.getCFHeadersForAllPeers
This function returns empty headers since at this early stage the peers list is empty.
The empty list is translated into an error which causes the chainWatcher to fail on its Start function and triggers the whole LND shutdown.

**Comment by halseth** [comment]
Thanks for the report! This issue should be fixed by https://github.com/lightninglabs/neutrino/pull/96

**Comment by roeierez** [comment]
This is great! thanks.
